// save map as a .room.gmx file

// special thanks:
// https://marketplace.yoyogames.com/assets/4221/derpxml

var namefile = get_open_filename("Name File|*.json", "");
if (namefile == "")
    exit;
    
var f = file_text_open_read(namefile);
var str = file_text_read_string_all(f);
file_text_close(f);

var namemap = json_decode(str);
if (namemap == -1)
{
    show_message("Wrong name file !");   
    exit;
}

var filename = get_save_filename("GMS1 Room|*.room.gmx", "");
if (filename == "")
    exit;

DerpXmlWrite_New();
DerpXmlWrite_Config('    ', chr(10));

DerpXmlWrite_Comment('This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!');
DerpXmlWrite_OpenTag("room");
    DerpXmlWrite_OpenTag("width");
        DerpXmlWrite_Text("800");
    DerpXmlWrite_CloseTag();
    
    DerpXmlWrite_OpenTag("height");
        DerpXmlWrite_Text("608");
    DerpXmlWrite_CloseTag();
    
    DerpXmlWrite_OpenTag("speed");
        DerpXmlWrite_Text("50");
    DerpXmlWrite_CloseTag();
    
    DerpXmlWrite_OpenTag("vsnap");
        DerpXmlWrite_Text("32");
    DerpXmlWrite_CloseTag();
    
    DerpXmlWrite_OpenTag("hsnap");
        DerpXmlWrite_Text("32");
    DerpXmlWrite_CloseTag();
    
    DerpXmlWrite_OpenTag("enableViews");
        DerpXmlWrite_Text("-1");
    DerpXmlWrite_CloseTag();
    
    DerpXmlWrite_OpenTag("views");
        DerpXmlWrite_LeafElement("view", "");
        DerpXmlWrite_Attribute("visible", "-1");
        DerpXmlWrite_Attribute("objName", "&lt;undefined&gt;");
        DerpXmlWrite_Attribute("xview", "0");
        DerpXmlWrite_Attribute("yview", "0");
        DerpXmlWrite_Attribute("wview", "800");
        DerpXmlWrite_Attribute("hview", "608");
        DerpXmlWrite_Attribute("xport", "0");
        DerpXmlWrite_Attribute("yport", "0");
        DerpXmlWrite_Attribute("wport", "800");
        DerpXmlWrite_Attribute("hport", "608");
        DerpXmlWrite_Attribute("hborder", "400");
        DerpXmlWrite_Attribute("vborder", "304");
        DerpXmlWrite_Attribute("hspeed", "-1");
        DerpXmlWrite_Attribute("vspeed", "-1");
    DerpXmlWrite_CloseTag();
    
    DerpXmlWrite_OpenTag("instances");
        with (all)
        {
            if (!objectInPalette(object_index))
                continue;
                
            if (!ds_map_exists(namemap, object_get_name(object_index)))
                continue;
                
            var maxpos = 896;
            var minpos = -128;
            if (x >= maxpos || y >= maxpos || x < minpos || y < minpos)
                continue;
                
            DerpXmlWrite_LeafElement("instance", "");;
            DerpXmlWrite_Attribute("objName", ds_map_find_value(namemap, object_get_name(object_index)));
            DerpXmlWrite_Attribute("x", string(x));
            DerpXmlWrite_Attribute("y", string(y));
            DerpXmlWrite_Attribute("name", "inst_" + randomInstanceID());
            DerpXmlWrite_Attribute("locked", "0");
            DerpXmlWrite_Attribute("code", "");
            DerpXmlWrite_Attribute("scaleX", "1");
            DerpXmlWrite_Attribute("scaleY", "1");
            DerpXmlWrite_Attribute("colour", "4294967295");
            DerpXmlWrite_Attribute("rotation", "0");
        }
    DerpXmlWrite_CloseTag();
DerpXmlWrite_CloseTag();
    
var xmlString = DerpXmlWrite_GetString();
DerpXmlWrite_UnloadString();

var f = file_text_open_write(filename);
file_text_write_string(f, xmlString);
file_text_close(f);

ds_map_destroy(namemap);

